#
###################################
# Site wide configuration
####################################
#
title: the philly code experiment
email: jessica.wray@gmail.com
description:
url: http://jesswray.com # the base hostname & protocol for your site
keywords: ["Programming", "Javascript", "Ruby", "React"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jessica Wray
  avatar: ic_build.png
  job: "Web Developer"
  bio: "Ruby and Javascript developer. Former costumer. Philadelphia"
  email: jessica.wray@gmail.com
  disqus-shortname:
  twitter: jessicaswray #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: wrayjs #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: wrayjessica #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
